language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11
install: true
script:
  - make install

jobs:
  include:
    - stage: deploy
      script: 'cp .ci-settings.xml $HOME/.m2/settings.xml && mvn clean deploy -Denforcer.skip=true -Dsnoozy.dev'
      jdk: openjdk8
      if: tag IS present

