language: java
jdk:
- oraclejdk8
- oraclejdk11
- openjdk8
- openjdk11
script:
- make install
before_deploy:
- cp .ci-settings.xml $HOME/.m2/settings.xml
deploy:
  - provider: script
    skip_cleanup: true
    on:
      tags: true
    script: 'mvn clean deploy -Denforcer.skip=true -Dsnoozy.dev'
